Add storage.md section to docs
greencloudcomputing/docs pull request #37
Opened 2024-05-29 09:49 UTC by JamesLDeveloper

Added new Storage Section to Guide.

Have included steps on how to create and access storage.

2024-05-29 12:59 UTC, tomaswarynyca commented on docs/guide/storage.md
> + $ 	gccli fx public
```suggestion
 $ gccli fx public
```

2024-05-29 12:59 UTC, tomaswarynyca commented on docs/guide/storage.md
> + $  gccli fx deploy
```suggestion
 $ gccli fx deploy
```

2024-05-29 13:00 UTC, tomaswarynyca commented on docs/guide/storage.md
> +📦️ Archs: AMD64,ARM64,ARM
```suggestion
📦️ Archs: AMD64
```

2024-05-29 13:00 UTC, tomaswarynyca commented on docs/guide/storage.md
> +🔗 Any existing endpoint will be revoked
```suggestion
```

2024-05-29 13:04 UTC, tomaswarynyca commented on docs/guide/storage.md
> +	}, err
```suggestion
	// set storage
	newStorage := base64.StdEncoding.EncodeToString([]byte("{\"admin\":1,\"password\":\"rich\"}"))
	headers.Set("GC-Storage", newStorage)

	return handler.Response{
		Body:       []byte("I am a storage Test!"),
		StatusCode: http.StatusOK,
		Header:     http.Header{
		"Content-Type": []string{"text/plain; charset=utf-8"},
	    },
	}, err
```

2024-05-29 19:45 UTC, tomaswarynyca requested changes
You are showing how to set the storage but never how to get it back.

```
// get storage
storage := req.Header.Get("GC-Storage")
text, _ := base64.StdEncoding.DecodeString(storage)
```

```
// set storage
newStorage := base64.StdEncoding.EncodeToString([]byte({\"user\":\"admin\",\"password\":\"rich\"}"))
headers.Set("GC-Storage", newStorage)
```

2024-05-31 13:39 UTC, JamesLDeveloper commented
> You are showing how to set the storage but never how to get it back.
> 
> ```
> // get storage
> storage := req.Header.Get("GC-Storage")
> text, _ := base64.StdEncoding.DecodeString(storage)
> ```
> 
> ```
> // set storage
> newStorage := base64.StdEncoding.EncodeToString([]byte({\"user\":\"admin\",\"password\":\"rich\"}"))
> headers.Set("GC-Storage", newStorage)
> ```

I've commited a change, please can you take another look and see if it is ok now?

2024-06-03 16:16 UTC, tomaswarynyca requested changes
Adding examples we've been looking at via Slack

2024-06-09 17:27 UTC, JamesLDeveloper commented
Added examples in tabs and changed storage size from 16mb to 1mb. Push is showing both a storage.md and Storage.md. Not sure which will actually be updated in the repo. Thanks

2024-06-18 21:54 UTC, tomaswarynyca approved these changes

2024-06-18 21:56 UTC, merged